name: DrugsConsume
version: ${project.version}
main: be.itsjust4you.drugsconsume.Main
authors: [ ItsJust4You ]
description: DrugsConsume Plugin

commands:
  consume:
    description: Main Command

permissions:
  drugsconsume.help:
    description: help menu
  drugsconsume.reload:
    description: reload